### ISSUE TITLE
Improve overflow of items page on small window

### ISSUE THREAD

**Issue by Nkmol** [Nkmol/RoC-Wiki#17]
![afbeelding](https://user-images.githubusercontent.com/8686001/48843198-b1e12600-ed96-11e8-984b-0287aa87d165.png)

**Comment by Nkmol** [comment]
The [BlockGallery](https://riseofcivilizations.wikia.com/wiki/Template:BlockGallery) items are now all one row. `flex-wrap` automatically wraps the individual items when they do not fit in their container anymore.

Added the following lines to define this:
```css
.block .wikia-gallery-row {
	flex-wrap: wrap;
	justify-content: center;
}
```
